version: '3.7'

services:
  gardena-client:
    container_name: gardena-client
    build:
      context: .
    restart: always
    environment:
      VIRTUAL_HOST: gardena.cloud.maevis.fr
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: gardena.cloud.maevis.fr
      LETSENCRYPT_EMAIL: bastien.tanesie@gmail.com
    volumes:
      - .:/srv/app
      - app_node_modules:/srv/app/node_modules

volumes:
  app_node_modules:

networks:
  default:
    external:
      name: nginx-proxy